### PR TITLE
File classes for review

### PR DESCRIPTION
**Pull request by planetarymike**
Following up from #23, this is a cleaner thread to discuss anything that needs to be changed before merging the new file classes into master. 

## Pull Request Checklist
 - [x] Code Follows PEP8 guidelines (explain any exceptions)
 - [x] New routines don't duplicate existing functionality
 - [x] Original authors of modified routines have been added as reviewers

### CODE REVIEW

**Comment by kconnour** [comment]
I'll look at this request periodically, but let me know when you have it in a finalized state and I'll give it a more thorough look.

**Comment by planetarymike** [comment]
I think this is ready for review now, I don't have any pending changes to commit.

**Review by kconnour — APPROVED** [review]
Looks fine! @zachariahmilby, any thoughts on your end? We're just now looping you into the conversation...

**Review by zachariahmilby — APPROVED** [review]
I am going to go ahead and presume that you two have worked this one out...

**Comment by planetarymike** [comment]
Hi Zac, you might want to confirm that renaming the file finding routines and changing the behavior to return an IUVSFITS is OK with you. Returning an IUVSFITS eliminates the need to separately import fits and open the files as a separate step. I modified the relevant search statements in your code to use the new routines, but I might have missed something.

**Pull request merged**
